apiVersion: apps/v1
kind: Deployment
metadata:
 name: reactjs
 namespace: default
 labels:
   app: reactjs
spec:
 replicas: 2
 selector:
  matchLabels:
   app: reactjs
 template:
  metadata:
   labels:
    app: reactjs
  spec:
   containers:
   - image: subodh624/reactfromdocker:280859baef92b4762db08f05ccabf3cf2df5176b
     name: reactjs
     ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  type: NodePort
  selector:
    app: reactjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
